name: video_progress_player
description: A Flutter video player built on top of video_player with resume watching, progress tracking, completion detection, and fullscreen support.
version: 0.0.1
repository: https://github.com/Coderkube-App/video_progress_player
homepage: https://github.com/Coderkube-App/video_progress_player
issue_tracker: https://github.com/Coderkube-App/video_progress_player/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.10.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player_platform_interface: ^6.7.0
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^6.0.0